apiVersion: v1
kind: Secret
metadata:
  name: etcd-oss
type: Opaque
data:
  accessKeyID: YWRtaW4K # admin
  accessKeySecret: YWRtaW4K # admin
  storageEndpoint: aHR0cHM6Ly9vc3MtY24taGFuZ3pob3UuYWxpeXVuY3MuY29tCg== # https://oss-cn-hangzhou.aliyuncs.com

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-tls
type: Opaque
data:
  tls.crt: encode-text
  tls.key: encode-text
  ca.crt: encode-text
